// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmtvkentpsyusnkugevc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdHZrZW50cHN5dXNua3VnZXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTM5NjQsImV4cCI6MjA3MDE4OTk2NH0.swzuYxB5tSJWVG1Oa6fvgQWpBV8cxIFXgacAsbi-SwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});